### ISSUE TITLE
multiple host occurences are ignored

### ISSUE THREAD

**Issue by mrkwtz** [txn2/txeh#2]
When there are multiple hosts with the same name in a hosts file only the first one will be updated on addHosts. See https://github.com/txn2/txeh/blob/master/txeh.go#L261

You can test this with the following hosts file 

127.0.0.1       abc
128.0.0.1       abc
129.0.0.1       abc

now try to add 130.0.0.1.

**Comment by cjimti** [comment]
@mrkwtz thanks for reporting this issue. However, there is no clear resolution since the example you gave is not a valid /etc/hosts configuration. `txeh` tries to treat the /etc/hosts just as your system does and only looks at the first entry.

Here is a good explanation: https://serverfault.com/questions/429839/assign-multiple-ips-to-1-entry-in-hosts-file/429851
