### ISSUE TITLE
Remove all entries that were created by txeh

### ISSUE THREAD

**Issue by Jneville0815** [txn2/txeh#28]
Is there currently a way to remove all entries that txeh created?

If not, would you be open to ideas or a PR submission?

**Comment by cjimti** [comment]
There is no clean way to do this that I have thought of. it would require storing what was added as a database of comments, prone to corruption by other processes or users themselves that may edit `/etc/hosts`. 

Also, I am assuming you are referring to the CLI and not the lib.

Problematic example:

```plain
127.0.0.2 some.domain some.domain.addedbytxeh some.domain.addedbyuser
```

Thoughts?

**Comment by Jneville0815** [comment]
I am using the library in a go project, not the CLI

But yeah that's a great point. Right now I'm using a hack where for each IP that I add using txeh, I add the necessary address and a dummy address. And then when I need to clean it up, just remove all addresses associated with the dummy address. This does make it prone to corruption like you mentioned.

I was thinking about adding comments to the host file to show what has been added by txeh. Something like this

```
127.0.0.2 some.domain some.domain.addedbytxeh some.domain.addedbyuser # some.domain.addedbytxeh
```

Not the cleanest solution but wouldn't interfere with other services

**Comment by cjimti** [comment]
It makes more sense to add this kind of functionality to your application IMO. 

I want to keep `txeh` simple and able to perform all its operations on properly formatted `/etc/hosts` without parsing any custom comment structures, etc. 

In addition, if two applications were using the library, there would have to be a way to differentiate them. Otherwise, an application might think it is okay to remove all those commented domains that another application added and does not want to remove. 

Also, end-of-line or inline comments are not officially supported by Windows:

https://support.microsoft.com/en-us/topic/how-to-reset-the-hosts-file-back-to-the-default-c2a43f9d-e176-c6f3-e4ef-3500277a6dae

> The Hosts file contains lines of text consisting of an IP address in the first text field followed by one or more host names. Each field is separated by white space (Tabs are often preferred for historical reasons, but spaces are also used). Comment lines may be included, and they are indicated by a hash character (#) in **the first position of such lines**. Entirely blank lines in the file are ignored.
